ALTER TABLE tenants
    ADD COLUMN IF NOT EXISTS billing_mode VARCHAR(50) NOT NULL DEFAULT 'SUBSCRIPTION_REQUIRED';

UPDATE tenants
SET billing_mode = 'SUBSCRIPTION_REQUIRED'
WHERE billing_mode IS NULL;
