CREATE TABLE IF NOT EXISTS tenants (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    cnpj VARCHAR(14),
    active BOOLEAN NOT NULL DEFAULT TRUE
);
